version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: IPSENHO-pipeline-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - network

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iprwc
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - network

networks:
  my-network:

volumes:
  db-data:
